# 定数定義

# 方向
D_NONE = 0
D_UP = 1
D_DOWN = 2
D_RIGHT = 3
D_LEFT = 4

# 敵情報配列
MOB_X = 0
MOB_Y = 1
MOB_DIRECTION = 2
MOB_RU = 3
MOB_RV = 4
MOB_LU = 5
MOB_LV = 6
MOB_STATE=7
MODE_TITLE = 0
MODE_SELECT = 1
MODE_FIELD = 2
MODE_BATTLE = 3
MODE_TEST = 4

# プレイヤーの状態
PLAYER_STATE_NORMAL = 0
PLAYER_STATE_MOVE   = 1
PLAYER_STATE_DAMAGE = 2
PLAYER_STATE_ATTACK = 3
PLAYER_STATE_DEAD = 4
PLAYER_STATE_LEVEL_UP_EFFECT = 5

# プレイヤー武器状態
PLAYER_WEAPON_SWORD = 0
PLAYER_WEAPON_MAGIC_FIRE = 1
PLAYER_WEAPON_MAGIC_THUNDER = 2

# プレイヤー職業
PLAYER_JOB_FIGHTER = 0
PLAYER_JOB_WIZARD = 1

# MOB状態
MOB_STATE_LIVE=0
MOB_STATE_DYING= 1
MOB_STATE_DEAD=2
MOB_STATE_MOVE = 3
MOB_STATE_STAY = 4
MOB_STATE_DAMAGE = 5
MOB_STATE_GENERATE = 6

# キャラクターピクセルサイズ
CHARACTER_PIXEL_SIZE=8

# BGM種類
BGM_NONE = -1
BGM_TITLE = 0
BGM_DUNGEON = 1
